### PR TITLE
Fixes #47: static use of SaltFactory

### LINKED ISSUE #47: Deprecated-function: Frontend crashes when typo3 make deprecated-exceptions
Dear Xavier,

we installed your OAuth-extension. 
After working through several errors, we finally got it to run!
Appreciate it!

One of the errors was:
`(1/1) #1476107295 TYPO3\CMS\Core\Error\Exception
PHP Runtime Deprecation Notice: Non-static method TYPO3\CMS\Core\Crypto\PasswordHashing\PasswordHashFactory::getDefaultHashInstance() should not be called statically in /html/typo3-dev1/public/typo3conf/ext/oidc/Classes/Service/AuthenticationService.php line 288

in /html/typo3-dev1/public/typo3/sysext/core/Classes/Error/ErrorHandler.php line 124
            E_DEPRECATED => 'PHP Runtime Deprecation Notice'
        ];
        $message = $errorLevels[$errorLevel] . ': ' . $errorMessage . ' in ' . $errorFile . ' line ' . $errorLine;
        if ($errorLevel & $this->exceptionalErrors) {
            throw new Exception($message, 1476107295);
        }
        switch ($errorLevel) {
            case E_USER_ERROR:
            case E_RECOVERABLE_ERROR:
at TYPO3\CMS\Core\Error\ErrorHandler->handleError(8192, 'Non-static method TYPO3\\CMS\\Core\\Crypto\\PasswordHashing\\PasswordHashFactory::getDefaultHashInstance() should not be called statically', '/html/typo3-dev1/public/typo3conf/ext/oidc/Classes/Service/AuthenticationService.php', 288, array('info' => array('sub' => '-2467653671196511184', 'email_verified' => false, 'email' => 'rotes.bueffelfell@web.de'), 'userTable' => 'fe_users', 'userGroupTable' => 'fe_groups', 'queryBuilder' => object(TYPO3\CMS\Core\Database\Query\QueryBuilder), 'row' => false, 'reEnableUser' => false, 'undeleteUser' => false, 'frontendUserMustExistLocally' => false, 'typo3Branch' => '9.5'))
in /html/typo3-dev1/public/typo3conf/ext/oidc/Classes/Service/AuthenticationService.php line 288
        $typo3Branch = class_exists(\TYPO3\CMS\Core\Information\Typo3Version::class)
            ? (new \TYPO3\CMS\Core\Information\Typo3Version())->getBranch()
            : TYPO3_branch;
        if (version_compare($typo3Branch, '9.0', '>=')) {
            $objInstanceSaltedPW = \TYPO3\CMS\Saltedpasswords\Salt\SaltFactory::getDefaultHashInstance(TYPO3_MODE);
        } else {
            $objInstanceSaltedPW = \TYPO3\CMS\Saltedpasswords\Salt\SaltFactory::getSaltingInstance(null, TYPO3_MODE);
        }
        $password = substr(str_shuffle('abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!@#$'), 0, 20);`

Means:
- Seemingly you use an old password-function to create the dummy-password;
- It's just a warning mit live-presets for debugging;
- When you increase sysloglevel to include depreaction warnings, typo3 thows an exception in the frontend

=> May you pleae adapt this?

Then it is less dangerous to fall into that trap.

Thank you,
Thomas

### PR DESCRIPTION
**Pull request by j-schumann**
v1.0.0 of the extension uses `SaltFactory::getDefaultHashInstance(TYPO3_MODE)` instead of the `GeneralUtility::makeInstance(SaltFactory::class)->getDefaultHashInstance(TYPO3_MODE)` suggested in the [developers guide](https://docs.typo3.org/c/typo3/cms-saltedpasswords/master/en-us/DevelopersGuide/Index.html). 

This causes errors like this:
```
Core: Error handler (FE): PHP Runtime Deprecation Notice: Non-static method TYPO3\CMS\Core\Crypto\PasswordHashing\PasswordHashFactory::getDefaultHashInstance() should not be called statically in [...]/typo3conf/ext/oidc/Classes/Service/AuthenticationService.php line 288
```

This PR fixes this error & #47.

### CODE REVIEW

File: Classes/Service/AuthenticationService.php [hunk 1]
```diff
@@ -285,7 +285,8 @@ protected function convertResourceOwner(array $info)
             ? (new \TYPO3\CMS\Core\Information\Typo3Version())->getBranch()
             : TYPO3_branch;
         if (version_compare($typo3Branch, '9.0', '>=')) {
-            $objInstanceSaltedPW = \TYPO3\CMS\Saltedpasswords\Salt\SaltFactory::getDefaultHashInstance(TYPO3_MODE);
+            $saltFactory = GeneralUtility::makeInstance(\TYPO3\CMS\Saltedpasswords\Salt\SaltFactory::class);
```
Comment (xperseguers) [inline Classes/Service/AuthenticationService.php:288]: `Saltedpasswords` is deprecated, the correct class to instantiate and method to call should be `\TYPO3\CMS\Core\Crypto\PasswordHashing\PasswordHashFactory::getDefaultHashInstance`

**Review by xperseguers — CHANGES_REQUESTED** [review]

File: Classes/Service/AuthenticationService.php (hunk 1 above)
Comment (j-schumann) [reply Classes/Service/AuthenticationService.php]: Changed in 698cfaa

**Review by xperseguers — APPROVED** [review]
